### ISSUE TITLE
Can not connect to calibre server with authentication enabled.

### ISSUE THREAD

**Issue by Nriver** [edrlab/thorium-reader#1829]
Tried to connect to my calibre server which has enabled authentication. 

I can access the opds data in a web browser with correct credentials. Thorium does not ask me for credentials and the error message says "message: Unauthorized | url: https://xxxxx | type: text/plain;charset=UTF-8 | code: 1000".

**Comment by llemeurfr** [comment]
Hi, Are you using the embedded OPDS server provided by Calibre? Are you using the latest Calibre version?

**Comment by llemeurfr** [comment]
FRom what we see in the Calibre open codebase, the current limitation is that Calibre does not support the OPDS Authentication spec (https://drafts.opds.io/authentication-for-opds-1.0.html). We have to see is we could support basic Authentication in Thorium without the provision of an Authentication Document.

**Comment by llemeurfr** [comment]
The use case is interesting, as Thorium cannot compete (currently) with Calibre for the flexibility in managing publication (choice of the storage folder ...), but Calibre cannot compete with Thorium for the quality of EPUB 3 reading features.

**Comment by panaC** [comment]
calibre http content server require authentication for cover 
https://github.com/kovidgoyal/calibre/blob/320dff52a6cbf8ddb927e9fe8b3e98c291756a43/src/calibre/srv/content.py#L292

need to set a specific endpoint with `auth_required=False`

**Comment by panaC** [comment]
> Start the content server
![Screenshot 2022-10-10 at 11 28 26](https://user-images.githubusercontent.com/3198865/194836328-fe4806de-fe96-47de-ae50-ffd121c381e5.png)
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/3198865/194834968-50e66a2f-3319-4c2d-8aa1-1601b4d9d2d4.png">



> Add an opds feed in thorium
![image](https://user-images.githubusercontent.com/3198865/194835329-d59084fb-6278-4843-a9b0-1afa194fab04.png)

> set the name and the url of the calibre opds feed ( http://127.0.0.1/opds )
![image](https://user-images.githubusercontent.com/3198865/194835671-adb8619c-1818-4388-ad04-182992559082.png)

> Click on the blue box with 'the name of the feed' and then fill your username and password
![image](https://user-images.githubusercontent.com/3198865/194835832-d76cab11-f6de-4b39-9ce1-1761be855e90.png)

> you can now access to your opds calibre feed
![image](https://user-images.githubusercontent.com/3198865/194835987-7ad4fe84-5668-4158-a0a8-47096d751b43.png)
![image](https://user-images.githubusercontent.com/3198865/194836013-1fb8edba-bd94-43d7-8694-d57d15825ce1.png)

**Comment by panaC** [comment]
@gautierchomel I wonder if we can add it to the thorium documentation ?

**Comment by llemeurfr** [comment]
I suppose that the Calibre server is also easily accessible from its intranet (aka home) wifi IP address. It allows having Thorium or any other mobile app accessing Calibre installed on a separate computer ... it would be great to address this in the doc.

**Comment by llemeurfr** [comment]
And, in the doc we should avoid showing both Calibre authentication and covers in Thorium ...

**Comment by panaC** [comment]
@llemeurfr fixed now https://github.com/edrlab/thorium-reader/pull/1832/commits/fc63762cd499f636dae700f096c3ba5ab50f98f6

**Comment by createchange** [comment]
Hi, I came across this thread when I received the same error message that the OP posted.

Following the directions posted in https://github.com/edrlab/thorium-reader/issues/1829#issuecomment-1273036970 didn't resolve the issue. 

When I disable authentication, the feed loads up just fine.

I am on Thorium v2.1.0, and Calibre 6.8.0.

**Comment by danielweck** [comment]
Hello, could you please try the latest developer / tester build from the release section of this GitHub repository.

**Comment by createchange** [comment]
Worked like a charm - thanks Daniel!
